services:
    site:
        image: jekyll/jekyll:latest
        command: jekyll serve --force_polling
        # command: jekyll serve --watch --incremental
        volumes:
          - ./:/srv/jekyll
        ports:
          - 4000:4000